-- CreateEnum
CREATE TYPE "RecoveryAction" AS ENUM ('MONITOR_INVOICE', 'SEND_EMAIL_REMINDER', 'SEND_WHATSAPP_REMINDER', 'SEND_PAYMENT_LINK', 'WAIT_FOR_PROMISED_PAYMENT', 'SEND_PROMISE_REMINDER', 'HUMAN_REVIEW_REQUIRED');

-- AlterEnum
ALTER TYPE "AuditEventType" ADD VALUE 'NEXT_ACTION_RECOMMENDED';

-- AlterTable
ALTER TABLE "Invoice" ADD COLUMN     "actionReason" TEXT NOT NULL DEFAULT 'Invoice is being monitored.',
ADD COLUMN     "recommendedAction" "RecoveryAction" NOT NULL DEFAULT 'MONITOR_INVOICE';
